Add nullability extensions
messerli-informatik-ag/utility pull request #9
Opened 2019-08-08 07:14 UTC by bash

2019-08-08 07:51 UTC, janhohenheim requested changes
Add the changes to the changelog and bump the version

2019-08-13 09:22 UTC, janhohenheim requested changes

2019-08-13 09:22 UTC, jnferner commented on .travis.yml
> +language: csharp
revert this and the next line

2019-08-13 09:23 UTC, janhohenheim submitted a review, later dismissed

2019-08-20 12:35 UTC, bash commented
Closing in favour of #10

2019-08-20 12:35 UTC, closed without merging

2019-08-20 12:36 UTC, janhohenheim reviewed
Per discussion: We actually use `foo is { }` now.